### ISSUE TITLE
Когда открываю прграмму  вылезает ошибка

### ISSUE THREAD

**Issue by Sskywwy** [Seeroy/kubek-minecraft-dashboard#10]
![kjVbEOkaxi](https://user-images.githubusercontent.com/99243052/162373943-34227a01-4f1d-4478-bbb1-90097bc5d445.png)
что делать?

**Comment by Seeroy** [comment]
Ошибка актуальна?

**Comment by maksim8560** [comment]
Тоже самое

**Comment by Seeroy** [comment]
Closed due to creator inactivity
Закрыто из-за неактивности создателя
