### ISSUE TITLE
Здраствуйте, ошибка при моей сборке как я понял:

### ISSUE THREAD

**Issue by 1VicTim1** [Seeroy/kubek-minecraft-dashboard#101]
после сборки исходников командой: pkg -t node*-win-x64 app.js
приложение стало овощем, при запуске показывает лого и в лог выдаёт "false" и всё...

**Comment by Seeroy** [comment]
Для сборки нужно использовать pkgconfig.json, который есть в исходниках

**Comment by 1VicTim1** [comment]
при его использовании выводится это: Error! No available node version satisfies 'node20'
версия node: 20.18.0
версия npm 10.8.2

**Comment by Seeroy** [comment]
pkg от Vercel уже в статусе deprecated. Нужно использовать этот https://github.com/yao-pkg/pkg

**Comment by 1VicTim1** [comment]
pkg -v
6.0.0

**Comment by 1VicTim1** [comment]
обновил, ничего не поменялось

**Comment by 1VicTim1** [comment]
немного подправил под свою кривую систему конфиг и пошла сборка, сейчас отпишу о работосповобности приложения

**Comment by 1VicTim1** [comment]
всё работает, спасибо огромное за помощь)
