### ISSUE TITLE
Linux start script

### ISSUE THREAD

**Issue by BasToTheMax** [Seeroy/kubek-minecraft-dashboard#15]
Hello!

On the moment you create a `start.bat`, but this works only on Windows.
https://github.com/Seeroy/kubek-minecraft-dashboard/blob/main/my_modules/servers.js#L24
You should add a function that checks what file extention to use.

If you don't want to do this, I can make a pull request.

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v1.2.7

**Comment by BasToTheMax** [comment]
Thx
