### ISSUE TITLE
Cyrillic text in console

### ISSUE THREAD

**Issue by MattysLouw** [Seeroy/kubek-minecraft-dashboard#26]
I've noticed that cyrillic output in console somehow gets broken. No problem with it when using RCON or in normal shell on the remote machine, however gets corrupted in console. It also gets recognized as WINDOWS-1251.

OS: Debian 11
`locale` output:
```
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Changing LC_ALL for the environment where Kubek starts does not help as well.

![image](https://user-images.githubusercontent.com/127508372/224330359-31cc9fb3-5e34-40e9-8b68-e290b8f7c42e.png)

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.10
Try it and close issue, if everything is alright

**Comment by MattysLouw** [comment]
Works fine now. Thank you.
