### ISSUE TITLE
Custom server stop command

### ISSUE THREAD

**Issue by MattysLouw** [Seeroy/kubek-minecraft-dashboard#27]
I've noticed that "Stop" action actually sends `stop` to the server.

This is nice on the one hand, but when it comes to Bungee or some pre-shudown actions – it won't work.

It would be pleasant to have an ability to change start and stop command in server's settings somewhere.

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.10
Try it and close issue, if everything is alright

**Comment by MattysLouw** [comment]
Works exactly as it should. Thank you.
