### ISSUE TITLE
Change port 112 to something else

### ISSUE THREAD

**Issue by MattysLouw** [Seeroy/kubek-minecraft-dashboard#28]
Port 112 used in `www/js/funcs.js` and `app.js` is not only hard-coded and is being used from the web, but also requires start from root on Linux to be used.

It would be nice to have an ability to have it higher than 1024 by default, and also to make it completely internal. Accessing one more port from outside the firewall is not the best concept.

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.10
Try it and close issue, if everything is alright

**Comment by MattysLouw** [comment]
Port 3001 does work now and is a solution for local usage without SSL, but this won't resolve a problem with being started behind reverse-proxy.

I get mixed content blocking if Kubek is behind nginx with SSL and socket is not, as well as it gets broken if I lead socket through SSL. Replacing `ws://` to `https://` in `www/js/funcs.js` does not work too. It crashes.

I still suggest hiding communications with socket in the main connection because opening additional port in firewall only for socket does not seem to be a good concept as well as leads to different problems when reverse-proxying to enable SSL.

Is it possible to combine communication of the socket and the main address or maybe make those communications internal for the Kubek itself, not leaving local network at all?

**Comment by Seeroy** [comment]
Try to use this files and send me feedback please

[replace js files.zip](https://github.com/Seeroy/kubek-minecraft-dashboard/files/10948203/replace.js.files.zip)

**Comment by MattysLouw** [comment]
Does not seem to work.
Web still tries to access socket by its port from outside the local network.
Kubek hangs on https://kb.domain.com on port 443.

![Screenshot from 2023-03-11 11-25-50](https://user-images.githubusercontent.com/127508372/224479250-4b64c820-ba65-4f6e-954e-67652dc7914f.jpg)

Nginx setup:
```nginx
server {
    listen 80;
    server_name kb.domain.com;

    return 301 https://kb.domain.com$request_uri;
}

server {
    listen 443 ssl;

    server_name kb.domain.com;

    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2; # do not use SSLv3 ref: POODLE

    error_page 497 https://$host$request_uri;

    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Port 443;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:3080/;
    }
}
```

By the way, I tried adding another nginx server to handle socket connections from 3001 and proxy them to localhost:3000, but it also does not work because socket won't accept redirect. Accessing from browser however redirects ok.
```nginx
server {
    listen kb.domain.com:3001 ssl;
    ssl on;
    ssl_certificate /etc/letsencrypt/live/domain.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/domain.com/privkey.pem;
    error_page 497 https://$host:3001$request_uri;
    location / {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Host $host;
        proxy_set_header X-Forwarded-Proto https;
        proxy_pass http://127.0.0.1:3000/;
    }
}
```

**Comment by Seeroy** [comment]
May be try to change protocol in www/js/funcs.js from http to https, and port, if it's non-standard

**Comment by MattysLouw** [comment]
Reverted back to 3000. Still does not seem to work.
Changing to https in `funcs.js` line 13 results in `Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://kb.domain.com:3000/socket.io/?EIO=4&transport=polling&t=ORGK0fd. (Reason: CORS request did not succeed). Status code: (null).`

**Comment by MattysLouw** [comment]
Oh. Completely removing port from that string in `funcs.js` did the trick. I forgot that it's already accessing the address with 443. It works like this:
```js
function openSocket() {
    return io("https://" + window.location.hostname);
}
```

**Comment by MattysLouw** [comment]
Yeah, in the end it works this way. Maybe a config option for port and using like that behind proxy?
Would be nice to switch to using this without changing the code.

**Comment by Seeroy** [comment]
Can you please try replacing https:// to ws:// in funcs.js. Is it gonna work? Because when using ws protocol, it may be automatically switching to neccessary protocol

**Comment by MattysLouw** [comment]
Unfortunately, it's reverting to http for some reason

**Comment by Seeroy** [comment]
Ok, thank you. May be i add "SSL Mode" in future updates. Close the issue if it is no longer required

**Comment by MattysLouw** [comment]
Alright. Thank you.
