### ISSUE TITLE
Несколько проблем с релизом 2.0.13-2.0.14

### ISSUE THREAD

**Issue by Andrew-Rayand** [Seeroy/kubek-minecraft-dashboard#34]
Приветствую, Seeroy!
Есть несколько проблем с Кубиком.

- Ошибка:
Error: The client timed out while connecting to 127.0.0.1:30002
    at Timeout._onTimeout (C:\snapshot\kubek-minecraft-dashboard\node_modules\minecraft-status\src\MinecraftQuery.class.js:106:13)
    at listOnTimeout (node:internal/timers:561:11)
    at processTimers (node:internal/timers:502:7)

Происходит с каждым запущенным сервером. Ошибка появляется каждые 4-5 секунд. Веб-интерфейс Кубика крашится примерно через 17 часов после запуска. Имеется связка серверов Velocity: прокси и два обычных 1.19.3 сервера с ViaVersion. Может, не хватает каких либо библиотек?

- Проблема с отображением кириллицы и спецсимволов в консоли. Вместо символов отображается знак "��"

- Не создается учётная запись пользователя с паролем, использующим специальные символы.
- Не создается учетная запись пользователя без ввода e-mail
- Некорректно работает автоперезагрузка сервера (плагин Ultimate AutoReload). Сервер останавливается и не включается. Хотелось бы видеть опцию автоперезагрузки в интерфейсе.

ID для технической поддержки: fe1b59db91eccd4ffb7f7f8d24a40de0
Машина: выделенный хост - win server 2022 на виртуалке.
Если потребуется дополнительная информация предоставлю ответным сообщением, заранее благодарю!

p.s. От себя могу добавить: спасибо за работу, всё классно, желаю успехов в разработке Кубика.

**Comment by Andrew-Rayand** [comment]
Ошибка:
Error: The client timed out while connecting to 127.0.0.1:30002
at Timeout._onTimeout (C:\snapshot\kubek-minecraft-dashboard\node_modules\minecraft-status\src\MinecraftQuery.class.js:106:13)
at listOnTimeout (node:internal/timers:561:11)
at processTimers (node:internal/timers:502:7)

...была связана с тем, что неправильно были выставлены настройки query.port=xxxxx значение должно совпадать с server-port=xxxxx

Но возникла новая:
при "убийстве" (крестик) сервера консоль nodejs выдает следующее:
[23:32:08.714] [127.0.0.1] GET - 200 - /server/kill?server=RaywoodTest
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'callback' is invalid. Received {
  env: {
    windir: 'C:\\Windows',
    USERPROFILE: 'C:\\Users\\Администратор',
    USERNAME: 'Администратор',
    USERDOMAIN...
    at new NodeError (node:internal/errors:372:5)
    at Object.execFile (node:child_process:305:11)
    at Object.execFile (pkg/prelude/bootstrap.js:2094:30)
    at Object.exec (node:child_process:225:25)
    at exec (pkg/prelude/bootstrap.js:2108:26)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\tree-kill\index.js:29:9
    at C:\snapshot\kubek-minecraft-dashboard\routers\server.js
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:346:12)
    at next (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:280:10)
    at C:\snapshot\kubek-minecraft-dashboard\routers\server.js
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:328:13)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:346:12)
    at next (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:175:3)
    at router (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:47:12)

**Comment by Seeroy** [comment]
Спасибо, будет исправлено/реализовано сегодня-зввтра.
`Проблема с отображением кириллицы и спецсимволов в консоли. Вместо символов отображается знак`
Подскажи, а сервера были добавлены до обновления 2.0.10, или уже после? Такая проблема с кодировкой возникает со всеми серверами, или только с серверами на конкретных ядрах?

**Comment by Seeroy** [comment]
`Веб-интерфейс Кубика крашится примерно через 17 часов после запуска` что ты имеешь ввиду под веб-интерфейсом? Есть ли при этом какие-то ошибки в консоли Кубека?

**Comment by Andrew-Rayand** [comment]
> Спасибо, будет исправлено/реализовано сегодня-зввтра. `Проблема с отображением кириллицы и спецсимволов в консоли. Вместо символов отображается знак` Подскажи, а сервера были добавлены до обновления 2.0.10, или уже после? Такая проблема с кодировкой возникает со всеми серверами, или только с серверами на конкретных ядрах?

Сервера были добавлены в версии 2.0.13

**Comment by Andrew-Rayand** [comment]
> `Веб-интерфейс Кубика крашится примерно через 17 часов после запуска` что ты имеешь ввиду под веб-интерфейсом? Есть ли при этом какие-то ошибки в консоли Кубека?

Ну интерфейс который в браузере на порту 3000
Консоль просто зависла, при этом серверы продолжили работу, за исключением того, у которого есть плагин на перезагрузку. Веб сайт был недоступен.

Можно ли в батнике прописать автовключение обратно, через goto, сработает ли это с кубиком, чтобы сервер после перезагрузки/краша восстанавливался?

**Comment by Andrew-Rayand** [comment]
> `Можно ли в батнике прописать автовключение обратно, через goto, сработает ли это с кубиком, чтобы сервер после перезагрузки/краша восстанавливался?` Я думаю лучше найти, в чем проблема, а не использовать костыли. Проведу тесты
> 
> `Проблема возникает на всех ядрах: проверял velocity, paper 1.19.3/1.19.4` Какой язык стоит в системе, в браузере и в Kubek?

Язык везде установлен русский. Использую chromium. Кубик русский.

**Comment by Seeroy** [comment]
> * Проблема с отображением кириллицы и спецсимволов в консоли. Вместо символов отображается знак "��"

Только что проверил, кириллица на версии 1.19.4 Paper отображается, подумаю. А можешь привести примеры спец. символов, которые таким образом отображаются?

**Comment by Seeroy** [comment]
![изображение](https://user-images.githubusercontent.com/37861929/228188522-1f7872d8-5b61-4f92-8edd-8470040182c1.png)

**Comment by Andrew-Rayand** [comment]
> > * Проблема с отображением кириллицы и спецсимволов в консоли. Вместо символов отображается знак "��"
> 
> Только что проверил, кириллица на версии 1.19.4 Paper отображается, подумаю. А можешь привести примеры спец. символов, которые таким образом отображаются?

Конечно, вот пример
![Screenshot_2023-03-28-12-27-34-607_com android chrome](https://user-images.githubusercontent.com/116679297/228192767-1b13c1d5-a3b6-43fc-8402-10d1800db970.jpg)

Проблема на любом хром подобном браузере

**Comment by Seeroy** [comment]
Проверьте пожалуйста всё то, о чём вы писали в [этой версии](https://cloud.mail.ru/public/u6iJ/QMMn1VZXv). Напишите, что теперь исправлено, а что ещё нужно исправить. Спасибо
P.S. Перезапуск сервера автоматически теперь возможен, нужное время/дата указываются в синтаксисе Crontab

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.15
Напишите, что теперь исправлено, а что ещё нужно исправить.

**Comment by Andrew-Rayand** [comment]
> https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.15 Напишите, что теперь исправлено, а что ещё нужно исправить.

- Ошибка с отображением кириллицы не исправилась.
- Всё еще не работает кнопка "стоп сервера"
Ошибка:
[19:15:47.528] [127.0.0.1] GET - 200 - /server/kill?server=RaywoodTest
TypeError [ERR_INVALID_ARG_VALUE]: The argument 'callback' is invalid. Received {
  env: {
    __COMPAT_LAYER: 'DetectorsAppHealth',
    windir: 'C:\\Windows',
    USERPROFILE: 'C:\\Users\\Администратор',
   ...
    at new NodeError (node:internal/errors:372:5)
    at Object.execFile (node:child_process:305:11)
    at Object.execFile (pkg/prelude/bootstrap.js:2094:30)
    at Object.exec (node:child_process:225:25)
    at exec (pkg/prelude/bootstrap.js:2108:26)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\tree-kill\index.js:29:9
    at C:\snapshot\kubek-minecraft-dashboard\routers\server.js
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\route.js:144:13)
    at Route.dispatch (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\route.js:114:3)
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:284:15
    at Function.process_params (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:346:12)
    at next (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:280:10)
    at C:\snapshot\kubek-minecraft-dashboard\routers\server.js
    at Layer.handle [as handle_request] (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:328:13)
    at C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:286:9
    at Function.process_params (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:346:12)
    at next (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:280:10)
    at Function.handle (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:175:3)
    at router (C:\snapshot\kubek-minecraft-dashboard\node_modules\express\lib\router\index.js:47:12)

- Предыдущая версия 2.0.14 также не продержалась 24 часа в сети, nodejs упал. Уточни, как вытащить логи для тебя.

![image](https://user-images.githubusercontent.com/116679297/228305875-19579ee0-31e0-4c1f-a2c8-d3e6130d8bcd.png)

**Comment by Andrew-Rayand** [comment]
> Обновитесь ещё до [этой версии](https://cloud.mail.ru/public/4mNn/b7mMwmbea) пожалуйста, проблему с OTP исправил вроде

- Проблема с ОТР ушла (еще не подключал ОТР).
- Сервер принудительно останавливается

- Проблема с кириллицей осталась
- Кубик не останавливает сервер при нажатии на "Выключить кубик". Ошибок не выдает.

**Comment by Andrew-Rayand** [comment]
В процессе тестирования обнаружилось еще несколько проблем:

- Не изменяется почта уже созданного пользователя
- Не создается учетная запись от пользователя, имеющего доступ к настройке Kubek. Создать возможно только от УЗ kubek
- Не создается учетная запись от любой учетной записи имеющей доступ к настройкам Кубика, содержащая пароль со специальным символом "!" "@" "#" "%" и.т.д... Кнопка сохранить прожимается, окно не уходит, УЗ не создается. При этом пароль FTP со спецсимволом создать можно.
- Проблема с кириллицей в консоли, при чем некоторые спецсимволы могут отображаться и со знаком "?", не только с "�". Вводимые команды отображаются кириллицей корректно.

Может быть на моем сервере не хватает каких либо библиотек для NodeJS или не установлены шрифты?

**Comment by Seeroy** [comment]
Спасибо, исправлю в следующем обновлении. Насчёт кодировки, попробую повторить вашу ситуацию, когда время будет. У меня ни на Windows 11, ни на Ubuntu 20.04 нет никаких проблем с кодировкой при любых раскладах.

**Comment by Andrew-Rayand** [comment]
> Спасибо, исправлю в следующем обновлении. Насчёт кодировки, попробую повторить вашу ситуацию, когда время будет. У меня ни на Windows 11, ни на Ubuntu 20.04 нет никаких проблем с кодировкой при любых раскладах.

Прошу еще проверить работоспособен ли FTP на Kubek. Соединение проходит, но файлзилла пишет, что 

- Статус:	Соединение установлено, ожидание приглашения...
Статус:	Небезопасный сервер, не поддерживает FTP через TLS.
Статус:	Сервер не поддерживает символы не ASCII.
Статус:	Авторизовались
Статус:	Получение списка каталогов...
Команда:	PWD
Ответ:	257 "\" is current directory
Команда:	TYPE I
Ответ:	200 OK
Команда:	PASV
Ответ:	227 Entering Passive Mode (127,0,0,1,4,1)
Команда:	LIST
Ответ:	150 Here comes the directory listing
Ошибка:	Соединение передачи данных не может быть установлено: ECONNREFUSED - Соединение отклонено сервером

**Comment by Seeroy** [comment]
Хорошо, проверю. А попробуй поставить Kubek к себе на компьютер, если есть возможность. И проверь, есть ли проблема с кодировкой в таком случае

**Comment by Seeroy** [comment]
Скинь ещё скриншот своих настроек из FileZilla (конф. данные замажь)

**Comment by Seeroy** [comment]
И плюсом, может у вас есть какие-то идеи для нововведений?

**Comment by Seeroy** [comment]
> * Не изменяется почта уже созданного пользователя
> 
> * Не создается учетная запись от пользователя, имеющего доступ к настройке Kubek. Создать возможно только от УЗ kubek

Не обнаружил такой проблемы. Можешь выложить по шагам полностью для повторения?

> Прошу еще проверить работоспособен ли FTP на Kubek. Соединение проходит, но файлзилла пишет, что

Проверил и через FileZilla и через WinSCP, подключается и на локальный, и на удалённый Kubek. Возможно что-то неправильно с настроками, например, брандмауэра?

Проверьте [этот релиз](https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.16)

**Comment by Andrew-Rayand** [comment]
> > * Не изменяется почта уже созданного пользователя
> > * Не создается учетная запись от пользователя, имеющего доступ к настройке Kubek. Создать возможно только от УЗ kubek
> 
> Не обнаружил такой проблемы. Можешь выложить по шагам полностью для повторения?
> 
> > Прошу еще проверить работоспособен ли FTP на Kubek. Соединение проходит, но файлзилла пишет, что
> 
> Проверил и через FileZilla и через WinSCP, подключается и на локальный, и на удалённый Kubek. Возможно что-то неправильно с настроками, например, брандмауэра?
> 
> Проверьте [этот релиз](https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.16)

Могу проверить, предоставить после 19 по МСК
Брандмауэр отключал, проблема остаётся.
Из предложений: 
- сделать инструкцию на гитхаб по работе модуля перезагрузки с небольшим ликбезом и корректными примерами для kubek (генератор ставит несколько пробелов, когда нужен один между звездами, неочевидно). Модуль работает, сервер перезагружается.
- Не отображаются цвета из консоли сервера (неудобно когда нет возможности проверить работают плагины или нет по команде ./pl когда команда отключена в игре). Сделать отображение цветов текста.
- добавить вывод подтверждения действия при остановке сервера (стоп, килл)
- при выключении кубика вывести уведомление что кубик выключен
- возможность делать бекап раз в опредленное время и в кастомный путь, например на сетевой диск.

p.s. Kubek снова упал. Логи вложу вечером.

**Comment by Seeroy** [comment]
> * добавить вывод подтверждения действия при остановке сервера (стоп, килл)

Это есть в последнем обновлении, по крайней мере на килл

> * сделать инструкцию на гитхаб по работе модуля перезагрузки с небольшим ликбезом и корректными примерами для kubek (генератор ставит несколько пробелов, когда нужен один между звездами, неочевидно). Модуль работает, сервер перезагружается.

К сожалению там такой прикол, что Java сама определяет, в каком она терминале запущена, и в зависимости от этого выводит цвета или не выводит. Но над этим тоже подумаю

> * возможность делать бекап раз в опредленное время и в кастомный путь, например на сетевой диск.

Возможно позже завезу полноценный планировщик

> * сделать инструкцию на гитхаб по работе модуля перезагрузки с небольшим ликбезом и корректными примерами для kubek (генератор ставит несколько пробелов, когда нужен один между звездами, неочевидно). Модуль работает, сервер перезагружается.

Окей

> * при выключении кубика вывести уведомление что кубик выключен

Окей

**Comment by Seeroy** [comment]
Исправлю в новом обновлении. Но логи всё равно кинь плз

**Comment by Andrew-Rayand** [comment]
[logdebug-gh2.txt](https://github.com/Seeroy/kubek-minecraft-dashboard/files/11104467/logdebug-gh2.txt)
[logdebug-gh.txt](https://github.com/Seeroy/kubek-minecraft-dashboard/files/11104468/logdebug-gh.txt)

gh-2 когда сервер крашнулся

**Comment by Andrew-Rayand** [comment]
Вчера не удалось проверить на компьютере отображение кириллицей.
Обновился на новый релиз, в целом по ощущениям стало стабильнее. Посмотрим вылетит ли сегодня.
Удалось изменить почту другому пользователю.
Мобильная версия работает хорошо, только помельче бы интерфейс. Есть баг с длинными названиями плагинов, ползунок сужается, а переключалка (кружок) остаётся на месте.
Предупреждения при килле сервера работают. 
Проблема с кириллицей остаётся.

**Comment by Seeroy** [comment]
Попробуй [эту версию](https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.17), здесь краши должны быть исправлены.

**Comment by Andrew-Rayand** [comment]
> Попробуй [эту версию](https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.17), здесь краши должны быть исправлены.

Обновился, стало приятнее с телефона, протестирую вечером с компьютера последний релиз.

**Comment by Andrew-Rayand** [comment]
Все хорошо, кубик стабилен, не крашит.
Версия последняя. 
Seeroy, все же как можно попробовать исправить проблему с отображением кириллицы?

**Comment by Seeroy** [comment]
Скиньте пожалуйста start.bat из папки сервера, на котором возникает проблема. У меня такой проблемы не было ни на Windows 11, ни на Ubuntu

**Comment by Andrew-Rayand** [comment]
> Скиньте пожалуйста start.bat из папки сервера, на котором возникает проблема. У меня такой проблемы не было ни на Windows 11, ни на Ubuntu

@echo off
chcp 65001>nul
cd servers
cd RaywoodTest
"C:/Program Files/Java/jdk-18.0.1.1/bin/java.exe" -Dfile.encoding=UTF-8 -Xmx1024M -XX:+UseG1GC -XX:+ParallelRefProcEnabled -XX:MaxGCPauseMillis=200 -XX:+UnlockExperimentalVMOptions -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -XX:G1HeapWastePercent=5 -XX:G1MixedGCCountTarget=4 -XX:G1MixedGCLiveThresholdPercent=90 -XX:G1RSetUpdatingPauseTimePercent=5 -XX:SurvivorRatio=32 -XX:+PerfDisableSharedMem -XX:MaxTenuringThreshold=1 -XX:G1NewSizePercent=30 -XX:G1MaxNewSizePercent=40 -XX:G1HeapRegionSize=8M -XX:G1ReservePercent=20 -XX:InitiatingHeapOccupancyPercent=15 -jar server.jar nogui
