### ISSUE TITLE
Подключение существующего paper сервера

### ISSUE THREAD

**Issue by wondersalmon** [Seeroy/kubek-minecraft-dashboard#35]
Как можно подключить уже существующий paper сервер распологающийся на том же хосте что и дашборд?

**Comment by Seeroy** [comment]
Создать в Kubek сервер с таким же ядром и переместить в папку с созданным сервером (папка Kubek/servers/название сервера) всё файлы вашего сервера, кроме файла запуска и файла ядра

**Comment by wondersalmon** [comment]
забыл закрыть. спасибо, помогло
