### ISSUE TITLE
Error: error

### ISSUE THREAD

**Issue by MrReijii** [Seeroy/kubek-minecraft-dashboard#38]
Добрый день! При попытке установить сервер Forge выдает окно "Error: error" и ничего не происходит, помогает только F5 и процесс установки сервера начинается сначала. Пробовал разные версии Forge, везде одно и то же. Ради эксперимента сунул ему файл forge-1.18.2-40.2.0-universal из папки с установленным сервером, файл был принят и началась загрузка java.*, далее сообщение "Распаковка завершена, подождите". На этом все замирает. В папке с серверами создалась папка с названием сервера, в ней лежит тот самый forge-1.18.2-40.2.0-universal, папка jdk-18.0.2.1+1 и eula.txt. в консоли ошибка об отсутствии run.sh.
Что я делаю не так? И как правильно установить ядро Forge? 
Спасибо

**Comment by Seeroy** [comment]
Для правильной установки ядра Forge нужно скачать версию Installer (**не** Universal), загрузить её как своё ядро. Установка пройдёт автоматически. Если что-то не получается - попробуйте другой браузер (реком. Firefox)
