### ISSUE TITLE
Улучшение телеграм бота

### ISSUE THREAD

**Issue by wondersalmon** [Seeroy/kubek-minecraft-dashboard#39]
Добрый день. Использую Kubek на одном сервере есть такие проблемы с телеграм ботом

1.  Кнопка "Статусы серверов" не работает
2.  Так как сервер один было бы здорово иметь возможность в боте выбрать сервер по умолчанию. Сейчас команды в телеграме по нажатию не работают, так как к ним нужно дописывать сервер. то есть приходится копировать например 
`/restartServer name` и вставлять в чат. Если есть возможность как то установить сервер по умолчанию или использовать конкретный сервер, если он один - было бы здорово. Правда для команды /execCommand это не сработает так как команду тоже надо вводить руками, если бы после нажатия на execcommand появлялся запрос на ввод команды - было бы идеально.

и еще баг - бот периодически забывает otp пароль если бот находится в групповом чате

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.1.0
Пункт 2 сделан в данной версии. Пункт 1 не обнаружен
