### ISSUE TITLE
Выбор своего порта(-ов) при запуске

### ISSUE THREAD

**Issue by BUCKLOGAN** [Seeroy/kubek-minecraft-dashboard#41]
Добавь возможность, чтобы при запуске (например на винде) можно было настроить свои порты для работы приложения

Например чтобы можно было переназначить 21, 3000, 3001 порты
Сделать настройку в отдельном конфиг файле, или при запуске спрашивало какой порт выбрать

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.0.19

**Comment by BUCKLOGAN** [comment]
Спасибо❤
