### ISSUE TITLE
Ограниченная учетка 

### ISSUE THREAD

**Issue by REDGROUL** [Seeroy/kubek-minecraft-dashboard#43]
Если зайти под учеткой у которой нет полных прав и перейти в раздел "информация о системе" то вечная загрузка и ошибка в консоли:
funcs.js:117 Uncaught TypeError: socket.emit is not a function
    at Object.success (funcs.js:117:18)
    at c (jquery-3.6.0.min.js:2:28327)
    at Object.fireWith [as resolveWith] (jquery-3.6.0.min.js:2:29072)
    at l (jquery-3.6.0.min.js:2:79901)
    at XMLHttpRequest.<anonymous> (jquery-3.6.0.min.

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.1.0
Проверьте, есть ли баг на этой версии

**Comment by REDGROUL** [comment]
Сейчас я вообще не могу добавить еще одну учетку.
Сервер работает на ubuntu server 22.04 права на users.json стоят 0777. Где то еще права выдать нужно ?
Включение авторизации работает с стандартными правами.

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.1.1
Проверьте, есть ли баг на этой версии

P.S. После включения авторизации вам нужно сначала **сохранить настройки Kubek**, войти в аккаунт администратора (если потребуется), и только тогда уже будет работать добавление новых пользователей. Теперь об этом так же есть уведомление (при включении переключателя авторизации)
