### ISSUE TITLE
Не запускается Forge srever 

### ISSUE THREAD

**Issue by REDGROUL** [Seeroy/kubek-minecraft-dashboard#44]
Не запускается forge сервер, ошибка в файле start.sh. Ошибка номер 2. Ошибка в строчке @libraries/net/minecraftforge/forge/1.19.2-43.2.13/unix_args.txt". Тут не хватает кавычек перд @, т.е. строка должна выглядеть так "@libraries/net/minecraftforge/forge/1.19.2-43.2.13/unix_args.txt". Но после ругается что не нашел либы по этому пути

**Comment by Seeroy** [comment]
Проблема найдена, в ближайшие несколько дней будет исправлена. Благодарю

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.1.1
Проверьте, есть ли баг на этой версии

**Comment by REDGROUL** [comment]
все работает, спасибо !
