### ISSUE TITLE
Соединение с сервером потеряно

### ISSUE THREAD

**Issue by murashkayt** [Seeroy/kubek-minecraft-dashboard#45]
Постоянно появляется уведомление "Соединение с сервером потеряно", когда включена вкладка консоли.
В консоли браузера появляется ошибка:
Access to XMLHttpRequest at `http://localhost:3001/socket.io/?EIO=4&transport=polling&t=OYCY92p` from origin `http://localhost:3000` has been blocked by CORS policy: The 'Access-Control-Allow-Origin' header has a value `http://localhost:3001` that is not equal to the supplied origin.
GET `http://localhost:3001/socket.io/?EIO=4&transport=polling&t=OYCY92p` net::ERR_FAILED 200 (OK)

**Comment by Seeroy** [comment]
Можно подробнее. Где установлен Kubek и с чего пытаетесь зайти. Открыты ли порты 3000 и 3001, если это требуется?

**Comment by murashkayt** [comment]
Kubek установлен в папке пользователя (`C:\Users\User\kubek`), пробовал заходить с Brave 1.52.122 (Chromium 114.0.5735.110) и Edge 114.0.1823.37. Порты 3000 и 3001 не открыты, так как я пользуюсь панелью внутри своей локальной сети.
На версии 2.1.2-hotfix проблема всё ещё актуальна. (В прошлый раз была 2.1.1)

**Comment by murashkayt** [comment]
Проблема решилась включением "Разрешить доступ с других IP". Все ошибки в консоли браузера и в веб-интерфейсе пропали.
