### ISSUE TITLE
Ошибка при попытке установки Bedrock сервера

### ISSUE THREAD

**Issue by LafayetteGPool** [Seeroy/kubek-minecraft-dashboard#48]
![WindowsTerminal_PcnJ4Iqtgc](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/88727912/4e259ae7-a3d9-40b3-af7d-6a94a3e76eae)
В панеле показывает что всё успешно и идёт скачивание, но подождав 5 мин ничего не менялось ни в панеле, ни в кансоле

**Comment by Seeroy** [comment]
Для исправления бага в данный момент вам нужно создать папку servers в папке кубека, перезапустить кубек и создать сервер заново. В следующем обновлении данный баг будет исправлен

**Comment by Seeroy** [comment]
Исправлено в данном обновлении
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.1.4
