### ISSUE TITLE
Над чем можно работать для Bedrock

### ISSUE THREAD

**Issue by LafayetteGPool** [Seeroy/kubek-minecraft-dashboard#49]
**Не показывает онлайн**

> ![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/88727912/e6ae9694-87d7-4b53-adcf-ffd8c8420177)

**Когда сервер полностью запустился показывает все равно что он еще запускается**

> ![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/88727912/5a03fbdc-62df-4140-a8ff-1f76eef360b6)

**server.properties пуст даже после запуска сервера и выключения**

> ![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/88727912/c6061a60-2229-4497-a761-973bbed2e558)

**так как это vanilla bedrock, вкладки с плагинами быть не может**

> ![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/88727912/e5a11858-603e-4ad0-a1a1-4fb9da8c6fda)

**Comment by Seeroy** [comment]
Проверьте данный релиз. К сожалению не всё было возможно выполнить в данный момент прямыми путями, поэтому на первом скриншоте теперь будут просто скрываться пункты про кол-во игроков и версию на Bedrock-серверах
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v2.1.5

После проверки закройте issue, если всё гуд, или напишите дополнения
