### ISSUE TITLE
Reverse proxy lost connection issue

### ISSUE THREAD

**Issue by taintedvalor** [Seeroy/kubek-minecraft-dashboard#50]
So every time I load up the reverse proxy stuff I set up for the dashboard it simply repeats lost connection it works as normal besides actual communication between the server and the dashboard and I don't know why or how to fix it if you have any ideas I'd appreciate it

**Comment by Seeroy** [comment]
This error occurs if the connection to websockets is lost.  Check the F12 console for errors and attach a screenshot if any.
P.S.  Socket ports on backend and frontend should not differ.  If you need such functionality, then you should build Kubek from source and slightly edit the socket connection function in the file www/js/functions.js

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v3.0.1
