### ISSUE TITLE
Добавление флагов "Aikar's Flags"

### ISSUE THREAD

**Issue by authorless** [Seeroy/kubek-minecraft-dashboard#53]
Хотелось бы увидеть функцию которая по нажатию кнопки переделает параметры запуска сервера под "Aikar's Flags". Я считаю это хорошим решением, а так же эти флаги довольно хорошо влияют на производительность сервера. Буду рад если данная функция сможет выйти в свет.

**Comment by Seeroy** [comment]
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/37861929/26600c76-5e8c-4fca-97e8-89c95a011767)
Разве это не та функция, о которой вы спрашиваете?

**Comment by authorless** [comment]
Так же под прокси прописываются дефолтные значения параметра запуска (Берется основное как и для сервера), хотя достаточно будет вот этих значений

Пример с 8 ОЗУ:
``
java -Xms8192M -Xmx8192M -XX:+UseG1GC -XX:G1HeapRegionSize=4M -XX:+UnlockExperimentalVMOptions -XX:+ParallelRefProcEnabled -XX:+AlwaysPreTouch -XX:MaxInlineLevel=15 -jar
``

**Comment by authorless** [comment]
Если нужно подробно откуда и как, то вот ссылка: [Aikar's Flags](https://flags.sh/)
