### ISSUE TITLE
Проблема с подключением к сайту через ngrok

### ISSUE THREAD

**Issue by zipmine** [Seeroy/kubek-minecraft-dashboard#54]
Здравствуйте, решил опробовать вашу программу, но возникла одна проблема.
Так как порты у меня не открыты и думаю что у меня серый айпи-адрес - решил попробовать подключаться через ngrok.

Открыл порт 3000 для сайта.
Открыл порт 25565 как основной порт сервера.
Открыл порт 25561 как дополнительный порт сервера. 
(В программе ngrok эти порты адресованы на localhost)

Всё получилось, но проблема заключается в том что если подключаться и взаимодействовать с сервером на сайте через localhost то всё прекрасно и быстро работает.
Но если подключаться на сайт по адресу и порту ngrok который был выдан в cmd то в уведомлениях каждые 10 секунд появляются сообщения "Соединение с сервером потеряно", при создании нового сервера все останавливается на самой первой закачке (проверке ядра или его скачивании), так же (если сервер уже был создан) при заходе в его панель - в консоли не отображаются новые сообщения, видны все кнопки, такие как "Запустить", "Остановить", "Предварительно остановить", "Перезапустить" и вместо значений "CPU" и "RAM" отображается "Неизвестно". 

При обновлении сайта/перезапуске компьютера ничего не меняется.
Вход на сайт осуществлялся с другого устройства на том же айпи.
Винда на устройстве где расположен Kubek абсолютно новая и чистая.

Мои предположения:
- Это происходит из-за высокого пинга от программы ngrok. Хотя в самой консоли программы пинг не привышал 200.
- Ошибка программы и/или сайта Kubek.

Приложу пару скриншотов с сайта
Не очень хорошо разбираюсь в этом. Надеюсь вы сможете мне помочь.
![Снимок экрана 2023-08-25 214123](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/73786112/d1267e8c-75ad-49c0-8efa-4c5d32bbd432)
![Снимок экрана 2023-08-25 214643](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/73786112/cc62ad2f-a77e-4dd4-a7a5-22bb31555f62)
![Снимок экрана 2023-08-25 215629](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/73786112/0d2355a5-d578-4bda-b080-989095bb7e26)

**Comment by zipmine** [comment]
Кажется понял в чем проблема. Наверное я забыл открыть порт 3001.
Сейчас попробую.

**Comment by zipmine** [comment]
Нет, проблема не решилась

**Comment by Seeroy** [comment]
Здравствуйте. Отправьте команды ngrok, используемые вами для создания туннелей, а так же отправьте скриншоты ошибок из консоли в браузере (Ctrl + F12)
В данный момент для исправления части проблем с Kubek его логика переписывается на Long Polling

**Comment by zipmine** [comment]
Для удобства был сделан один .bat файл запускающий другие файлы. Можно было бы организовать всё в одном но решил сделать так.

Один .bat файл запускает другие четыре в которых прописаны следующие команды:
cd OneDrive/Рабочий стол
ngrok config add-authtoken (токен первого аккаунта)
ngrok tcp 3000

cd OneDrive/Рабочий стол
ngrok config add-authtoken (токен второго аккаунта)
ngrok tcp 3001

cd OneDrive/Рабочий стол
ngrok config add-authtoken (токен третьего аккаунта)
ngrok tcp 25565

cd OneDrive/Рабочий стол
ngrok config add-authtoken (токен четвертого аккаунта)
ngrok tcp 25561

В каждом файле указаны разные токены аккаунтов, так как на одном аккаунте нельзя иметь больше одного соединения.
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/73786112/83c8dd46-d155-4c68-9bb1-6bb10f345c37)

**Comment by zipmine** [comment]
Вот скрин консолей ngrok:
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/73786112/f07c2eff-0ff6-4ad4-be66-96442a042942)

**Comment by zipmine** [comment]
Вот скриншот консолей ngrok:
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/73786112/5fd24b68-6aac-4c55-8be8-a1cdf40f7c15)

**Comment by zipmine** [comment]
Ожидаю ответа...

**Comment by Seeroy** [comment]
Сейчас через ngrok Kubek работать к сожалению не будет. Возможно в течение нескольких дней выпущу минорное обновление, где переведу Kubek на Long polling, и тогда всё будет работать

**Comment by zipmine** [comment]
Хорошо, буду очень ждать данного обновления.

**Comment by Seeroy** [comment]
Хотя попробовать решить это возможно. Проблема в том, что WS в моём софте работают через HTTP, а ngrok открывает туннели в HTTPS. Т.е. нужно каким-то образом сделать сокетам подключение HTTPS (WSS). Для этого нужно редактировать исходный код

**Comment by zipmine** [comment]
Ещё есть предложение небольшое. Очень неудобно удалять папки, так как нужно сначала удалить все файлы в ней, поэтому было бы хорошо это исправить, или добавить в настройках флажок, который будет включать или выключать данную функцию.

**Comment by Seeroy** [comment]
Проверьте существование проблемы:
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v3.0.0
