### ISSUE TITLE
Ошибка с кодом 1

### ISSUE THREAD

**Issue by Isatau** [Seeroy/kubek-minecraft-dashboard#55]
Когда нажимаю запустить то появляется уведомление с ошибка с кодом 1, а в консоль выводиться Killed.

**Comment by Isatau** [comment]
Абсалютно все ядра такая же ошибка, уже удалял и переустнавливал сам kubek

**Comment by Seeroy** [comment]
Подскажите, вы выбираете автоматическую установку Java, или используете свою версию. Версия панели? Версия и тип ядер, на которых возникает проблема?

**Comment by Isatau** [comment]
Понял почему она так делала. Оказывается в настройках сервера поставить галочку на java
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/64313853/6fdfa9d5-a83a-4905-abeb-e0adef3e5d9d)
