### ISSUE TITLE
Добавить существующий сервер

### ISSUE THREAD

**Issue by MozenZ** [Seeroy/kubek-minecraft-dashboard#56]
Возможно ли как-то добавить существующий сервер находящиеся не в главной папке кубца?

**Comment by kirik2020** [comment]
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/75547126/6e1ffd5d-40dd-49b3-901d-d1fa607c6828)
закидываешь папку с сервером и запускаешь
