### ISSUE TITLE
Проблема в отображении server.properties

### ISSUE THREAD

**Issue by kirik2020** [Seeroy/kubek-minecraft-dashboard#57]
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/75547126/01a150e3-5ce1-4f7f-8f7e-040f1b9d5c34)
и при первом заходе на сайт там вообще был белый квадрат
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/75547126/dac2a622-1c28-4ce9-bc7a-db37ea6abc6b)

**Comment by Seeroy** [comment]
О проблеме известно, в крупном обновлении будет переписан полностью фронт и проблема будет исправлена. Пока workaround'ом является использование Kubek через Firefox
