### ISSUE TITLE
Added Japanese translation

### ISSUE THREAD

**Issue by Rin-ad** [Seeroy/kubek-minecraft-dashboard#60]
Hello, and thank you for creating such a great tool.  
Now, I have created a Japanese translation file for Kubek.
I didn't have any knowledge of nodejs, so I couldn't add it to the language selection menu.
I have attached ja.json, so I would appreciate it if you could add it to the language selection menu.
[ja.json](https://github.com/Seeroy/kubek-minecraft-dashboard/files/13378426/ja.json)

**Comment by Seeroy** [comment]
Hello, thanks for your contribution to the development of the project! As soon as possible I will include your translation in a new build of the program. But I'm currently doing a very global update of the program, and therefore you may have to redo your translation a little

**Comment by Rin-ad** [comment]
Thank you for your consideration.

**Comment by Seeroy** [comment]
Greetings. Sorry for the long response, but update 3.0.0 is finally out. Can I ask you to translate it into Japanese for her? Files for translation in the new format are located in the languages ​​folder. You can also now specify the author of the translation, and it will be displayed in the list of languages
