### ISSUE TITLE
Невозможно работать с пользователями

### ISSUE THREAD

**Issue by t-lessy** [Seeroy/kubek-minecraft-dashboard#62]
Любое изменения в пользователях, кроме включения авторизации, выдаёт ошибку.
Так абсолютно с любым из них. Попытки создать нового через панель не удаются.

Пробовал добавить в users.json вручную, копируя стандартного, однако после добавления изменения всё так же безуспешны.

Пробовал изменять права файла users.json, но даже с полными правами для всех панель не может изменить юзеров.

**Логи панели**: [11-01-2024.log](https://github.com/Seeroy/kubek-minecraft-dashboard/files/13906090/11-01-2024.log)
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/69511001/c4780023-18cc-43b8-8151-060aeec63d53)

**Comment by Seeroy** [comment]
Проверьте существование бага на данной версии
[app-linux.zip](https://github.com/Seeroy/kubek-minecraft-dashboard/files/13907390/app-linux.zip)

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v3.0.1
