### ISSUE TITLE
Новая ошибка, не работает редактирование фаилов.

### ISSUE THREAD

**Issue by ClingingStas** [Seeroy/kubek-minecraft-dashboard#67]
Такая ошибка:
ReferenceError: crypto is not defined

**Comment by ClingingStas** [comment]
![Uploading Screenshot_20240127_143617.png…]()

**Comment by ClingingStas** [comment]
![Screenshot_20240127_143617](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/143094373/01263c9b-d44c-4e27-a510-0f3e91744f31)

**Comment by Seeroy** [comment]
Спасибо за скрин ошибки, очень помогло в исправлении. Проверьте на этой версии
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v3.0.3

**Comment by ClingingStas** [comment]
Да, вы исправили это. Теперь работает.
