### ISSUE TITLE
Маленкие ошибки интерфейса.

### ISSUE THREAD

**Issue by ClingingStas** [Seeroy/kubek-minecraft-dashboard#68]
Тут на нижних эолементах закругление появляется только при наведение
![Screenshot_20240128_224118](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/143094373/aca8a834-cb80-494a-9c81-f8df6beaeb5e)
Тут таблица настройки не сркугленна и не растянута на полный контейнер
![Screenshot_20240128_224217](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/143094373/03c047a4-c8ef-4d11-ae65-ed47551acd82)
Тут тоже углы глючат
![Screenshot_20240128_224425](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/143094373/affb4cff-3515-4468-b572-428ec928a43c)

**Comment by ClingingStas** [comment]
Оказывается что это глюки из-за браузера firefox

**Comment by Seeroy** [comment]
Некоторые косяки в стилях таблиц исправлены здесь
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v3.0.4

**Comment by ClingingStas** [comment]
теперь это действительно харошая алтернатива панели птеродактель.

**Comment by Seeroy** [comment]
Я не особо тянусь к Птере, как к эталону (только если по функционалу), ибо там и разрабов/контрибьютов гораздо больше, и используемые технологии вообще разные :)
