### ISSUE TITLE
Use websockets instead of http requests for getting statuses

### ISSUE THREAD

**Issue by BasToTheMax** [Seeroy/kubek-minecraft-dashboard#7]
![ZIJiMtSq](https://user-images.githubusercontent.com/55401336/160275988-f7405ea7-1ac5-4d2b-8853-eae51e9398eb.png)
Use **websockets** to get updates!

**Comment by Seeroy** [comment]
Ok, i will take it. Thanks

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v1.2
