### ISSUE TITLE
Маленкая ошибка.

### ISSUE THREAD

**Issue by ClingingStas** [Seeroy/kubek-minecraft-dashboard#70]
Я конечно понимаю что надоел со своими маленькими ошибками но мне казалось или кнопка сохранения должна быть внутри контейнера

**Comment by ClingingStas** [comment]
![Screenshot_20240129_113547](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/143094373/65b77c12-f337-4b52-9dda-a6736d7f9b61)

**Comment by ClingingStas** [comment]
Это маленькая ошибка а так ваша панель замечательная(даже если сравнивать с панелью птеродактель)

**Comment by Seeroy** [comment]
Кнопка сохранения специально сдвинута вниз в новой версии, так как в Настройках Kubek и Настройках сервера кнопка располагается на том же месте. Чтобы интерфейс этих разделов был однородным и привычным по управлению

**Comment by ClingingStas** [comment]
А почему в 'Настройках сервера' это не так работает.

**Comment by Seeroy** [comment]
По идее должно. Можно скрин?
