### ISSUE TITLE
fonts 404 | Не найдены шрифты

### ISSUE THREAD

**Issue by MeteoraCD2** [Seeroy/kubek-minecraft-dashboard#75]
Привет!
Супер мелкий косяк с шрифтами есть: то ли были переименованы когда-то, то ли удалены из репозитория. Детали на скриншоте
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/81615203/f26b5607-65e9-4be6-8e18-419efecc815d)
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/81615203/0dc32c5e-0be5-4fc7-a31e-069affb251b8)
Знаю, что могу сам исправить просто заменив, но решил оповестить, а на гитхабе не умею исправления предлагать

**Comment by Seeroy** [comment]
Кстати очень странная ситуация. У меня в локальной версии 20 файлов, как и должно быть. На Гитхабе их 14, но у меня Гитхаб не видит разницы между локальным и удалённым репозиториями. Возможно у меня как-то косячно .gitignore прописан...

**Comment by Seeroy** [comment]
Так и есть, селектор *old* шедеврален...
