### ISSUE TITLE
An error occurred while sending statistics

### ISSUE THREAD

**Issue by hRAGE** [Seeroy/kubek-minecraft-dashboard#82]
**Kubek 3.0.4** _(checked also on earlier versions)_.
**Node.js v21.7.2**.

When running Kubek, an error occurs while sending statistics, as shown in the console output below:
![Kubek 3 0 4-win-x64_Wy7jmbc9hZ](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/57248348/02e13f57-636c-4acd-b846-b223de7bf84f)

When I try to create a server. It ends at _"Added task with ID ... and type ..."_ stage, with no further progression of the process.

Suspecting what the problem might be, I used a VPN service and the issue was solved. The problem may be due to regional or other restrictions directed at your country.

**Comment by Seeroy** [comment]
Hello. I think the reason is that my domain is located in the .ru zone, and is only accessible from your country with VPN.
Unfortunately, the domain I need in .com and .org is too expensive for me, sorry
