### ISSUE TITLE
Проблема

### ISSUE THREAD

**Issue by Olegsabertoothed** [Seeroy/kubek-minecraft-dashboard#85]
Oops! An error occurred while fetching cores
![image](https://github.com/Seeroy/kubek-minecraft-dashboard/assets/171380516/fe1bf051-ad96-4cd7-82df-fabcc26fee6a)

**Comment by Seeroy** [comment]
Is the problem still relevant?
Where do you live, is the seeroy.ru domain available to you?

**Comment by MeteoraCD2** [comment]
When I create a new server and select a core Paper, I get this error in the logs, and the page stops working.
seeroy.ru and seeeroy.ru sites are available
```
:/kubek-minecraft-dashboard# curl https://seeroy.ru
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>cloudflare</center>
</body>
</html>
```
