### ISSUE TITLE
Split code into multiple files

### ISSUE THREAD

**Issue by BasToTheMax** [Seeroy/kubek-minecraft-dashboard#9]
Split the code into multiple files, because you currently have a really big file of over 1200 lines.

If you want, I can do this for you and then make a pull request!

**Comment by Seeroy** [comment]
I am currently splitting my code into modules. But thank you)

**Comment by BasToTheMax** [comment]
That is what I meant. Thx for doing this! :) 👍

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v1.2
