### ISSUE TITLE
Приветствую всех

### ISSUE THREAD

**Issue by lite629** [Seeroy/kubek-minecraft-dashboard#90]
Приветствую разработчик, у меня появилась проблема при запуске.Я когда запускаю там нету ссылки,либо подскажите как правильно качать я по гайду не понял. Вот мой дс san_Lite могу дэмку показать очень тяжело описать,там проще  объяснить проблему.Заранее спасибо

**Comment by MeteoraCD2** [comment]
Пиши, что не понятно, поможем. Сложного, вроде, ничего же нет, если всё по инструкции делать

**Comment by Seeroy** [comment]
Приветствую. Если на винде, то возможно проблема в том, что порт занят? Доступен ли в вашей локации сайт seeeroy.ru? Если нет, то попробуйте запустить Kubek с VPN
