### ISSUE TITLE
Используется следующая версия minecraft

### ISSUE THREAD

**Issue by SkinGad** [Seeroy/kubek-minecraft-dashboard#94]
Проблема следующая: При выборе версии ванильного майна 1.12.2 (Как пример) скачивается и сохраняется файл `vanilla-1.12.2.jar`, но при этом запускается 1.13.
Аналогично например с версией 1.19.2 ставится версия 1.19.3.
Реальная версия отображается в консоли, а так-же при попытке входа на сервер.
Вот пример:
![image](https://github.com/user-attachments/assets/60e81e25-7ec0-4267-a0c0-c7e86afc484e)
![image](https://github.com/user-attachments/assets/b1956c22-27d1-42ca-a6b7-cdbca306d5eb)
![image](https://github.com/user-attachments/assets/c1f9d453-f7bf-45d7-9cff-228bcbe11711)

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v3.0.6

**Comment by SkinGad** [comment]
Проверил, закрываю. Спасибо!
