### ISSUE TITLE
JSON bug on server.property save

### ISSUE THREAD

**Issue by UrSenpaiii** [Seeroy/kubek-minecraft-dashboard#95]
_Firefox 131.0 | Chrome 129.0.6668.90
Kubek 3.0.5_

При заходе на [/?act=server.properties](http://localhost:3000/?act=server.properties) в поле `generator-settings` подставляется поломанный JSON в виде `[object Object]` (любим JS :)) и при сохранении в файл естественно прописывается `[object Object]` и после этого сервер не будет запускаться, так как валуе `generator-settings` в файле server.property ни коем не похоже на JSON.
Ну плюсом может где-нибудь еще JSON так же багуется...

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v3.0.6
