### ISSUE TITLE
почему ломается server-ip?

### ISSUE THREAD

**Issue by showyxxx** [Seeroy/kubek-minecraft-dashboard#97]
![image](https://github.com/user-attachments/assets/999ae677-fbe5-4f4c-9206-3a2dcecee33f)

**Comment by showyxxx** [comment]
На месте цифр должен быть айпи с точками

**Comment by Seeroy** [comment]
https://github.com/Seeroy/kubek-minecraft-dashboard/releases/tag/v3.0.7

**Comment by showyxxx** [comment]
Все работает, спасибо 👍
